repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.0
    hooks:
      - id: codespell
        args: ["--ignore-words", "dict/allow.txt", "--skip", "*.lock,*.svg,webapp/static/js/*,docs-site/package-lock.json"]
  - repo: local
    hooks:
      - id: run-checks
        name: run project checks
        entry: bash scripts/checks.sh
        language: python
        additional_dependencies:
          - flake8
          - isort
          - black
          - pytest
          - linkchecker
          - requests
          - Flask
          - responses
          - trimesh
          - tabulate
          - bandit
          - safety
        pass_filenames: false
