repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: local
    hooks:
      - id: run-checks
        name: run project checks
        entry: bash scripts/checks.sh
        language: python
        additional_dependencies:
          - flake8
          - isort
          - black
          - pytest
          - linkchecker
          - requests
          - Flask
          - responses
          - trimesh
        pass_filenames: false

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.0
    hooks:
      - id: codespell
        args:
          - "--ignore-words=dict/allow.txt"
          - "--skip=*.lock,*.svg,*.min.js"
