name: Test Suite
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      matrix:
        language: [python, javascript]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup uv
        if: matrix.language == 'python'
        uses: astral-sh/setup-uv@v1

      - name: Python Tests (with coverage)
        if: matrix.language == 'python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - if: matrix.language == 'python'
        run: |
          uv pip install --system pytest pytest-cov coverage
          if [ -f requirements.txt ]; then uv pip install --system -r requirements.txt; fi
          pytest --cov=flywheel --cov-report=xml --cov-report=term --maxfail=1 --disable-warnings -q --cov-fail-under=100
          coverage report --fail-under=100

      - name: JavaScript Tests
        if: matrix.language == 'javascript'
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - if: matrix.language == 'javascript' && hashFiles('package.json') != ''
        run: |
          npm install --no-audit --no-fund
          npx playwright install --with-deps
          if [ -f webapp/requirements-playwright.txt ]; then \
            pip install --no-input -r webapp/requirements-playwright.txt; \
          fi
          npm test -- --coverage --coverageReporters=lcov

      # --- Upload coverage only if the matching report exists ---
      - name: Upload Python coverage
        if: >-
          matrix.language == 'python' &&
          hashFiles('coverage.xml') != '' &&
          env.CODECOV_TOKEN != ''
        uses: codecov/codecov-action@v4
        with:
          token: ${{ env.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: python
          fail_ci_if_error: false

      - name: Upload JS coverage
        if: >-
          matrix.language == 'javascript' &&
          hashFiles('coverage/lcov.info') != '' &&
          env.CODECOV_TOKEN != ''
        uses: codecov/codecov-action@v4
        with:
          token: ${{ env.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: javascript
          fail_ci_if_error: false
