name: Test Suite
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [python, javascript]
    steps:
      - uses: actions/checkout@v3

      - name: Setup uv
        if: matrix.language == 'python'
        uses: astral-sh/setup-uv@v1

      - name: Python Tests
        if: matrix.language == 'python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - if: matrix.language == 'python'
        run: |
          uv pip install --system pytest
          if [ -f requirements.txt ]; then uv pip install --system -r requirements.txt; fi
          pytest --maxfail=1 --disable-warnings -q

      - name: JavaScript Tests
        if: matrix.language == 'javascript'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - if: matrix.language == 'javascript' && hashFiles('package.json') != ''
        run: |
          npm install --no-audit --no-fund
          npm test -- --coverage
