name: Spelling
on: [push, pull_request]
jobs:
  spell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crate-ci/typos@v1
        with:
          config: .typos.toml
