name: Export SCAD to OBJ
on:
  push:
    paths:
      - 'hardware/cad/*.scad'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install OpenSCAD
        run: sudo apt-get update && sudo apt-get install -y openscad
      - name: Convert SCAD files
        run: |
          mkdir -p webapp/static/models
          for f in hardware/cad/*.scad; do
            base=$(basename "$f" .scad)
            openscad "$f" -o "webapp/static/models/$base.obj"
          done
      - name: Commit OBJ models
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add webapp/static/models/*.obj
          if git diff --cached --quiet; then
            echo "No OBJ changes to commit"
          else
            git commit -m "chore: update OBJ models"
            git push
          fi
