name: Build & Push Docker
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/docker/Dockerfile
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
          push: false
          load: true
      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/docker/Dockerfile
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
          push: true
