name: Export SCAD
on:
  push:
    paths:
      - 'cad/**'
      - '.github/workflows/export-scad.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install OpenSCAD
        run: sudo apt-get update && sudo apt-get install -y openscad
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install meshio
      - name: Convert SCAD to OBJ
        run: python scripts/export_scad_to_obj.py
      - uses: actions/upload-artifact@v3
        with:
          name: obj-models
          path: web/static/models/*.obj
