# .github/workflows/link-check.yml
name: Link Check

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  linkcheck:
    name: Lychee Link Checker
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.2.2

      - name: Cache Lychee
        id: cache-lychee
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # v4.3.0
        with:
          path: ~/.cache/lychee
          key: lychee-${{ runner.os }}-${{ hashFiles('**/*.md', '.lychee*') }}
          restore-keys: |
            lychee-${{ runner.os }}-

      - name: Run Lychee
        uses: lycheeverse/lychee-action@885c65f3dc543b57c898c8099f4e08c8afd178a2  # v2.6.1
        with:
          args: >-
            --no-progress
            --base ./
            --max-concurrency 6
            --max-retries 2
            --retry-wait-time 2
            --exclude-all-private
            --exclude-mail
            --exclude-loopback
            --accept 200,206,429
            --timeout 20
            --cache
            --config .lychee.toml
            --format detailed
            .

      - name: Upload Lychee Report
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: lychee-report
          path: lychee-report.txt
          if-no-files-found: ignore
