name: Nightly Repo Scan
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - uses: astral-sh/setup-uv@v1
      - run: |
          uv pip install --system -r requirements.txt
          uv pip install --system bandit safety
      - run: python -m flywheel.agents.scanner
      - uses: actions/upload-artifact@v4
        with:
          name: scan-reports
          path: reports/
